# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_NPCM_BPC)		+= npcm-bpc.o
obj-$(CONFIG_WPCM450_SOC)	+= wpcm450-soc.o
obj-$(CONFIG_NPCM_ESPI_MMBI) += npcm-espi-mmbi.o
obj-$(CONFIG_MTD_NPCM_TIP_FIU)	+= npcm_fiu_tip.o
obj-$(CONFIG_NPCM_ESPI_SLAVE) += npcm-espi-slave.o
obj-$(CONFIG_NPCM_TIP_RNG) += npcm-tip-rng.o
